spring:
  cache:
    type: redis
    redis:
      time-to-live: PT60M
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27018/offers
    redis:
      port: ${REDIS_PORT:63792}
      host: ${REDIS_HOST:localhost}

offer:
  fetchOffersOccurrence: "0 0 */3 * * ?"
  http:
    client:
      config:
        connectionTimeout: 1000
        readTimeout: 1000
        uri: http://ec2-3-127-218-34.eu-central-1.compute.amazonaws.com
        port: 5057

scheduling:
  enabled: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

auth:
  jwt:
    secret: ${JWT_SECRET}
    issuer: job-offers-backend
    expirationDays: 30

#
#logging:
#  level:
#    org:
#      springframework:
#        cache: DEBUG
#      data:
#        redis: DEBUG
